config/routes.rb
ThrowBreakTrainer::Application.routes.draw do
  root to: "main_game#throw_break_trainer"

  devise_for :users
  get "main_game/throw_break_trainer"
  resources :video_infos

  resources :high_scores

  resources :users

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
  end

end

app/models/video_info.rb
# == Schema Information
#
# Table name: video_infos
#
#  id                     :integer          not null, primary key
#  video_name             :string(255)
#  number_of_milliseconds :integer
#  created_at             :datetime
#  updated_at             :datetime
#

class VideoInfo < ActiveRecord::Base
end

app/controllers/video_infos_controller.rb
class VideoInfosController < ApplicationController
  before_action :set_video_info, only: [:show, :edit, :update, :destroy]

  # GET /video_infos
  # GET /video_infos.json
  def index
    @video_infos = VideoInfo.all
  end

  # GET /video_infos/1
  # GET /video_infos/1.json
  def show
  end

  # GET /video_infos/new
  def new
    @video_info = VideoInfo.new
  end

  # GET /video_infos/1/edit
  def edit
  end

  # POST /video_infos
  # POST /video_infos.json
  def create
    @video_info = VideoInfo.new(video_info_params)

    respond_to do |format|
      if @video_info.save
        format.html { redirect_to @video_info, notice: 'Video info was successfully created.' }
        format.json { render action: 'show', status: :created, location: @video_info }
      else
        format.html { render action: 'new' }
        format.json { render json: @video_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /video_infos/1
  # PATCH/PUT /video_infos/1.json
  def update
    respond_to do |format|
      if @video_info.update(video_info_params)
        format.html { redirect_to @video_info, notice: 'Video info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @video_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /video_infos/1
  # DELETE /video_infos/1.json
  def destroy
    @video_info.destroy
    respond_to do |format|
      format.html { redirect_to video_infos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video_info
      @video_info = VideoInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_info_params
      params.require(:video_info).permit(:video_name, :number_of_milliseconds)
    end
end

app/helpers/video_infos_helper.rb
module VideoInfosHelper
end

app/views/video_infos/_form.html.erb
<%= form_for(@video_info) do |f| %>
  <% if @video_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video_info.errors.count, "error") %> prohibited this video_info from being saved:</h2>

      <ul>
      <% @video_info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :video_name %><br>
    <%= f.text_field :video_name %>
  </div>
  <div class="field">
    <%= f.label :number_of_milliseconds %><br>
    <%= f.number_field :number_of_milliseconds %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/video_infos/edit.html.erb
<h1>Editing video_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @video_info %> |
<%= link_to 'Back', video_infos_path %>

app/views/video_infos/index.html.erb
<h1>Listing video_infos</h1>

<table>
  <thead>
    <tr>
      <th>Video name</th>
      <th>Number of milliseconds</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @video_infos.each do |video_info| %>
      <tr>
        <td><%= video_info.video_name %></td>
        <td><%= video_info.number_of_milliseconds %></td>
        <td><%= link_to 'Show', video_info %></td>
        <td><%= link_to 'Edit', edit_video_info_path(video_info) %></td>
        <td><%= link_to 'Destroy', video_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video info', new_video_info_path %>

app/views/video_infos/new.html.erb
<h1>New video_info</h1>

<%= render 'form' %>

<%= link_to 'Back', video_infos_path %>

app/views/video_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Video name:</strong>
  <%= @video_info.video_name %>
</p>

<p>
  <strong>Number of milliseconds:</strong>
  <%= @video_info.number_of_milliseconds %>
</p>

<%= link_to 'Edit', edit_video_info_path(@video_info) %> |
<%= link_to 'Back', video_infos_path %>